version: '3.1'

networks:
  backend:

services:
  mysql:
    image: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: charon
      MYSQL_USER: charon
      MYSQL_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - mysql
    networks:
      backend:

