server:
  port: 8082
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID #防止Cookie冲突，冲突会导致登录验证不通过
spring:
  application:
    name: charon-exchange
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/charon?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    locations: classpath:db/migration, classpath:db/migrationTest
    table: flyway_exchange_history
    baseline-version: 0
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2: #与oauth2-server对应的配置
    client:
      client-id: admin
      client-secret: admin123456
      user-authorization-uri: http://localhost:7072/oauth/authorize
      access-token-uri: http://localhost:7072/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:7072/oauth/token_key
