server:
  port: 7071
spring:
  application:
    name: charon-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: charon-exchange
          uri: lb://charon-exchange
          predicates:
          - Path= /exchange/**
          filters:
          - StripPrefix= 1
        - id: charon-auth
          uri: lb://charon-auth
          predicates:
            - Path= /auth/**
          filters:
            - StripPrefix= 1
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:7072/rsa/publicKey' #配置RSA的公钥访问地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



