server:
  port: 8081
spring:
  application:
    name: charon-user
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/charon?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    locations: classpath:db/migration, classpath:db/migrationTest
    table: flyway_user_history
    baseline-version: 0
    baseline-on-migrate: true